# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9008e2534708c4c3a5e8837d01b6568d8ad087fc0fee7efe860dc028f3d2ab7decce6870de4937e4e3c68f80dba8b264ccb6a4fc7bd9b4ca863ea3033bd416b7

test:
  secret_key_base: 61d77738b794da3ca71dfa06b6cebcc93023191bf3fd37dd465d1b512b54ae4bcb4dfe55993f4420ddbd6879fc17bb551f68b69bc217dc3c7ed2c8ad1c127c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
